/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 109
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 65
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 28
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_public = 1,
  anon_sym_function = 2,
  anon_sym_COLON = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_return = 7,
  anon_sym_SEMI = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_declare = 11,
  anon_sym_namespace = 12,
  anon_sym_entity = 13,
  anon_sym_DOT = 14,
  anon_sym_enum = 15,
  anon_sym_POUND = 16,
  anon_sym_field = 17,
  anon_sym_assert = 18,
  anon_sym_let = 19,
  anon_sym_EQ = 20,
  anon_sym_GT = 21,
  anon_sym_GT_EQ = 22,
  anon_sym_LT = 23,
  anon_sym_LT_EQ = 24,
  anon_sym_PLUS = 25,
  anon_sym_Int = 26,
  anon_sym_Nat = 27,
  anon_sym_CString = 28,
  anon_sym_String = 29,
  anon_sym_BigNat = 30,
  sym_num_lit = 31,
  sym_enum_tok = 32,
  sym_namespace_tok = 33,
  sym_identifier = 34,
  sym_source_file = 35,
  sym__components = 36,
  sym__function_def = 37,
  sym__parameters = 38,
  sym__return = 39,
  sym__statement_block = 40,
  sym__statement = 41,
  sym__namespace_def = 42,
  sym__entity = 43,
  sym__field_block = 44,
  sym__accessor = 45,
  sym__enum = 46,
  sym__enum_block = 47,
  sym__enum_value = 48,
  sym__enum_access = 49,
  sym__value = 50,
  sym__field = 51,
  sym__assertion = 52,
  sym__definition = 53,
  sym__expression = 54,
  sym__less_than = 55,
  sym__greater_than = 56,
  sym__addition = 57,
  sym__bind_id_to_type = 58,
  sym__type = 59,
  aux_sym_source_file_repeat1 = 60,
  aux_sym__parameters_repeat1 = 61,
  aux_sym__statement_block_repeat1 = 62,
  aux_sym__field_block_repeat1 = 63,
  aux_sym__enum_block_repeat1 = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_public] = "public",
  [anon_sym_function] = "function",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_return] = "return",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_declare] = "declare",
  [anon_sym_namespace] = "namespace",
  [anon_sym_entity] = "entity",
  [anon_sym_DOT] = ".",
  [anon_sym_enum] = "enum",
  [anon_sym_POUND] = "#",
  [anon_sym_field] = "field",
  [anon_sym_assert] = "assert",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_PLUS] = "+",
  [anon_sym_Int] = "Int",
  [anon_sym_Nat] = "Nat",
  [anon_sym_CString] = "CString",
  [anon_sym_String] = "String",
  [anon_sym_BigNat] = "BigNat",
  [sym_num_lit] = "num_lit",
  [sym_enum_tok] = "enum_tok",
  [sym_namespace_tok] = "namespace_tok",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__components] = "_components",
  [sym__function_def] = "_function_def",
  [sym__parameters] = "_parameters",
  [sym__return] = "_return",
  [sym__statement_block] = "_statement_block",
  [sym__statement] = "_statement",
  [sym__namespace_def] = "_namespace_def",
  [sym__entity] = "_entity",
  [sym__field_block] = "_field_block",
  [sym__accessor] = "_accessor",
  [sym__enum] = "_enum",
  [sym__enum_block] = "_enum_block",
  [sym__enum_value] = "_enum_value",
  [sym__enum_access] = "_enum_access",
  [sym__value] = "_value",
  [sym__field] = "_field",
  [sym__assertion] = "_assertion",
  [sym__definition] = "_definition",
  [sym__expression] = "_expression",
  [sym__less_than] = "_less_than",
  [sym__greater_than] = "_greater_than",
  [sym__addition] = "_addition",
  [sym__bind_id_to_type] = "_bind_id_to_type",
  [sym__type] = "_type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__parameters_repeat1] = "_parameters_repeat1",
  [aux_sym__statement_block_repeat1] = "_statement_block_repeat1",
  [aux_sym__field_block_repeat1] = "_field_block_repeat1",
  [aux_sym__enum_block_repeat1] = "_enum_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_public] = anon_sym_public,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_declare] = anon_sym_declare,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_entity] = anon_sym_entity,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_assert] = anon_sym_assert,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_Int] = anon_sym_Int,
  [anon_sym_Nat] = anon_sym_Nat,
  [anon_sym_CString] = anon_sym_CString,
  [anon_sym_String] = anon_sym_String,
  [anon_sym_BigNat] = anon_sym_BigNat,
  [sym_num_lit] = sym_num_lit,
  [sym_enum_tok] = sym_enum_tok,
  [sym_namespace_tok] = sym_namespace_tok,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__components] = sym__components,
  [sym__function_def] = sym__function_def,
  [sym__parameters] = sym__parameters,
  [sym__return] = sym__return,
  [sym__statement_block] = sym__statement_block,
  [sym__statement] = sym__statement,
  [sym__namespace_def] = sym__namespace_def,
  [sym__entity] = sym__entity,
  [sym__field_block] = sym__field_block,
  [sym__accessor] = sym__accessor,
  [sym__enum] = sym__enum,
  [sym__enum_block] = sym__enum_block,
  [sym__enum_value] = sym__enum_value,
  [sym__enum_access] = sym__enum_access,
  [sym__value] = sym__value,
  [sym__field] = sym__field,
  [sym__assertion] = sym__assertion,
  [sym__definition] = sym__definition,
  [sym__expression] = sym__expression,
  [sym__less_than] = sym__less_than,
  [sym__greater_than] = sym__greater_than,
  [sym__addition] = sym__addition,
  [sym__bind_id_to_type] = sym__bind_id_to_type,
  [sym__type] = sym__type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__parameters_repeat1] = aux_sym__parameters_repeat1,
  [aux_sym__statement_block_repeat1] = aux_sym__statement_block_repeat1,
  [aux_sym__field_block_repeat1] = aux_sym__field_block_repeat1,
  [aux_sym__enum_block_repeat1] = aux_sym__enum_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_public] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_declare] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entity] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assert] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Nat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CString] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BigNat] = {
    .visible = true,
    .named = false,
  },
  [sym_num_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_tok] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace_tok] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__components] = {
    .visible = false,
    .named = true,
  },
  [sym__function_def] = {
    .visible = false,
    .named = true,
  },
  [sym__parameters] = {
    .visible = false,
    .named = true,
  },
  [sym__return] = {
    .visible = false,
    .named = true,
  },
  [sym__statement_block] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__namespace_def] = {
    .visible = false,
    .named = true,
  },
  [sym__entity] = {
    .visible = false,
    .named = true,
  },
  [sym__field_block] = {
    .visible = false,
    .named = true,
  },
  [sym__accessor] = {
    .visible = false,
    .named = true,
  },
  [sym__enum] = {
    .visible = false,
    .named = true,
  },
  [sym__enum_block] = {
    .visible = false,
    .named = true,
  },
  [sym__enum_value] = {
    .visible = false,
    .named = true,
  },
  [sym__enum_access] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym__field] = {
    .visible = false,
    .named = true,
  },
  [sym__assertion] = {
    .visible = false,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__less_than] = {
    .visible = false,
    .named = true,
  },
  [sym__greater_than] = {
    .visible = false,
    .named = true,
  },
  [sym__addition] = {
    .visible = false,
    .named = true,
  },
  [sym__bind_id_to_type] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__field_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__enum_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bsq_prim = 1,
  field_entity_name = 2,
  field_enum_access = 3,
  field_enum_accessor = 4,
  field_enum_key = 5,
  field_enum_name = 6,
  field_enum_values = 7,
  field_field = 8,
  field_field_block = 9,
  field_func_body = 10,
  field_func_name = 11,
  field_keyword = 12,
  field_namespace_id = 13,
  field_params = 14,
  field_return_type = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bsq_prim] = "bsq_prim",
  [field_entity_name] = "entity_name",
  [field_enum_access] = "enum_access",
  [field_enum_accessor] = "enum_accessor",
  [field_enum_key] = "enum_key",
  [field_enum_name] = "enum_name",
  [field_enum_values] = "enum_values",
  [field_field] = "field",
  [field_field_block] = "field_block",
  [field_func_body] = "func_body",
  [field_func_name] = "func_name",
  [field_keyword] = "keyword",
  [field_namespace_id] = "namespace_id",
  [field_params] = "params",
  [field_return_type] = "return_type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 15},
  [2] = {.index = 15, .length = 8},
  [3] = {.index = 23, .length = 1},
  [4] = {.index = 24, .length = 5},
  [5] = {.index = 29, .length = 3},
  [6] = {.index = 32, .length = 30},
  [7] = {.index = 62, .length = 6},
  [8] = {.index = 68, .length = 3},
  [9] = {.index = 71, .length = 1},
  [10] = {.index = 72, .length = 8},
  [11] = {.index = 80, .length = 1},
  [12] = {.index = 81, .length = 3},
  [13] = {.index = 84, .length = 8},
  [14] = {.index = 92, .length = 1},
  [15] = {.index = 93, .length = 2},
  [16] = {.index = 95, .length = 3},
  [17] = {.index = 98, .length = 3},
  [18] = {.index = 101, .length = 6},
  [19] = {.index = 107, .length = 1},
  [20] = {.index = 108, .length = 10},
  [21] = {.index = 118, .length = 3},
  [22] = {.index = 121, .length = 4},
  [23] = {.index = 125, .length = 8},
  [24] = {.index = 133, .length = 2},
  [25] = {.index = 135, .length = 10},
  [26] = {.index = 145, .length = 3},
  [27] = {.index = 148, .length = 7},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_bsq_prim, 0, .inherited = true},
    {field_entity_name, 0, .inherited = true},
    {field_enum_access, 0, .inherited = true},
    {field_enum_accessor, 0, .inherited = true},
    {field_enum_key, 0, .inherited = true},
    {field_enum_name, 0, .inherited = true},
    {field_enum_values, 0, .inherited = true},
    {field_field, 0, .inherited = true},
    {field_field_block, 0, .inherited = true},
    {field_func_body, 0, .inherited = true},
    {field_func_name, 0, .inherited = true},
    {field_keyword, 0, .inherited = true},
    {field_namespace_id, 0, .inherited = true},
    {field_params, 0, .inherited = true},
    {field_return_type, 0, .inherited = true},
  [15] =
    {field_bsq_prim, 0, .inherited = true},
    {field_enum_access, 0, .inherited = true},
    {field_enum_accessor, 0, .inherited = true},
    {field_enum_name, 0, .inherited = true},
    {field_func_body, 0, .inherited = true},
    {field_func_name, 0, .inherited = true},
    {field_params, 0, .inherited = true},
    {field_return_type, 0, .inherited = true},
  [23] =
    {field_namespace_id, 0, .inherited = true},
  [24] =
    {field_bsq_prim, 0, .inherited = true},
    {field_entity_name, 0, .inherited = true},
    {field_field, 0, .inherited = true},
    {field_field_block, 0, .inherited = true},
    {field_keyword, 0, .inherited = true},
  [29] =
    {field_enum_key, 0, .inherited = true},
    {field_enum_name, 0, .inherited = true},
    {field_enum_values, 0, .inherited = true},
  [32] =
    {field_bsq_prim, 0, .inherited = true},
    {field_bsq_prim, 1, .inherited = true},
    {field_entity_name, 0, .inherited = true},
    {field_entity_name, 1, .inherited = true},
    {field_enum_access, 0, .inherited = true},
    {field_enum_access, 1, .inherited = true},
    {field_enum_accessor, 0, .inherited = true},
    {field_enum_accessor, 1, .inherited = true},
    {field_enum_key, 0, .inherited = true},
    {field_enum_key, 1, .inherited = true},
    {field_enum_name, 0, .inherited = true},
    {field_enum_name, 1, .inherited = true},
    {field_enum_values, 0, .inherited = true},
    {field_enum_values, 1, .inherited = true},
    {field_field, 0, .inherited = true},
    {field_field, 1, .inherited = true},
    {field_field_block, 0, .inherited = true},
    {field_field_block, 1, .inherited = true},
    {field_func_body, 0, .inherited = true},
    {field_func_body, 1, .inherited = true},
    {field_func_name, 0, .inherited = true},
    {field_func_name, 1, .inherited = true},
    {field_keyword, 0, .inherited = true},
    {field_keyword, 1, .inherited = true},
    {field_namespace_id, 0, .inherited = true},
    {field_namespace_id, 1, .inherited = true},
    {field_params, 0, .inherited = true},
    {field_params, 1, .inherited = true},
    {field_return_type, 0, .inherited = true},
    {field_return_type, 1, .inherited = true},
  [62] =
    {field_bsq_prim, 2, .inherited = true},
    {field_entity_name, 1},
    {field_field, 2, .inherited = true},
    {field_field_block, 2},
    {field_keyword, 0},
    {field_keyword, 2, .inherited = true},
  [68] =
    {field_enum_key, 0},
    {field_enum_name, 1},
    {field_enum_values, 2},
  [71] =
    {field_bsq_prim, 0, .inherited = true},
  [72] =
    {field_bsq_prim, 2, .inherited = true},
    {field_bsq_prim, 3, .inherited = true},
    {field_enum_access, 3, .inherited = true},
    {field_enum_accessor, 3, .inherited = true},
    {field_enum_name, 3, .inherited = true},
    {field_func_body, 3},
    {field_func_name, 1},
    {field_params, 2},
  [80] =
    {field_namespace_id, 2},
  [81] =
    {field_bsq_prim, 0, .inherited = true},
    {field_field, 0},
    {field_keyword, 0, .inherited = true},
  [84] =
    {field_bsq_prim, 3, .inherited = true},
    {field_bsq_prim, 4, .inherited = true},
    {field_enum_access, 4, .inherited = true},
    {field_enum_accessor, 4, .inherited = true},
    {field_enum_name, 4, .inherited = true},
    {field_func_body, 4},
    {field_func_name, 2},
    {field_params, 3},
  [92] =
    {field_bsq_prim, 1, .inherited = true},
  [93] =
    {field_bsq_prim, 0, .inherited = true},
    {field_bsq_prim, 1, .inherited = true},
  [95] =
    {field_enum_access, 0, .inherited = true},
    {field_enum_accessor, 0, .inherited = true},
    {field_enum_name, 0, .inherited = true},
  [98] =
    {field_bsq_prim, 1, .inherited = true},
    {field_field, 1, .inherited = true},
    {field_keyword, 1, .inherited = true},
  [101] =
    {field_bsq_prim, 0, .inherited = true},
    {field_bsq_prim, 1, .inherited = true},
    {field_field, 0, .inherited = true},
    {field_field, 1, .inherited = true},
    {field_keyword, 0, .inherited = true},
    {field_keyword, 1, .inherited = true},
  [107] =
    {field_bsq_prim, 2},
  [108] =
    {field_bsq_prim, 2, .inherited = true},
    {field_bsq_prim, 5, .inherited = true},
    {field_enum_access, 5, .inherited = true},
    {field_enum_accessor, 5, .inherited = true},
    {field_enum_name, 5, .inherited = true},
    {field_func_body, 5},
    {field_func_name, 1},
    {field_params, 2},
    {field_return_type, 3},
    {field_return_type, 4},
  [118] =
    {field_enum_access, 1, .inherited = true},
    {field_enum_accessor, 1, .inherited = true},
    {field_enum_name, 1, .inherited = true},
  [121] =
    {field_bsq_prim, 1, .inherited = true},
    {field_enum_access, 1, .inherited = true},
    {field_enum_accessor, 1, .inherited = true},
    {field_enum_name, 1, .inherited = true},
  [125] =
    {field_bsq_prim, 0, .inherited = true},
    {field_bsq_prim, 1, .inherited = true},
    {field_enum_access, 0, .inherited = true},
    {field_enum_access, 1, .inherited = true},
    {field_enum_accessor, 0, .inherited = true},
    {field_enum_accessor, 1, .inherited = true},
    {field_enum_name, 0, .inherited = true},
    {field_enum_name, 1, .inherited = true},
  [133] =
    {field_bsq_prim, 1, .inherited = true},
    {field_keyword, 0},
  [135] =
    {field_bsq_prim, 3, .inherited = true},
    {field_bsq_prim, 6, .inherited = true},
    {field_enum_access, 6, .inherited = true},
    {field_enum_accessor, 6, .inherited = true},
    {field_enum_name, 6, .inherited = true},
    {field_func_body, 6},
    {field_func_name, 2},
    {field_params, 3},
    {field_return_type, 4},
    {field_return_type, 5},
  [145] =
    {field_enum_access, 2},
    {field_enum_accessor, 1},
    {field_enum_name, 0},
  [148] =
    {field_bsq_prim, 1, .inherited = true},
    {field_enum_access, 1, .inherited = true},
    {field_enum_access, 2, .inherited = true},
    {field_enum_accessor, 1, .inherited = true},
    {field_enum_accessor, 2, .inherited = true},
    {field_enum_name, 1, .inherited = true},
    {field_enum_name, 2, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(73);
      ADVANCE_MAP(
        '#', 90,
        '(', 77,
        ')', 79,
        '+', 101,
        ',', 78,
        '.', 88,
        ':', 76,
        ';', 82,
        '<', 99,
        '=', 96,
        '>', 97,
        'B', 29,
        'C', 7,
        'S', 57,
        'a', 55,
        'd', 18,
        'e', 41,
        'f', 34,
        'l', 21,
        'p', 66,
        'r', 24,
        '{', 83,
        '}', 84,
        'I', 108,
        'N', 108,
        'i', 108,
        'n', 108,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(72);
      if (lookahead == ')') ADVANCE(79);
      if (lookahead == ',') ADVANCE(78);
      if (lookahead == ';') ADVANCE(82);
      if (lookahead == '=') ADVANCE(96);
      if (lookahead == '}') ADVANCE(84);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '$', 72,
        ';', 82,
        'a', 134,
        'l', 128,
        'r', 130,
        '}', 84,
        'I', 109,
        'N', 109,
        'i', 111,
        'n', 111,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(112);
      END_STATE();
    case 3:
      if (lookahead == '$') ADVANCE(72);
      if (lookahead == 'I' ||
          lookahead == 'N' ||
          lookahead == 'i' ||
          lookahead == 'n') ADVANCE(111);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 4:
      if (lookahead == ';') ADVANCE(82);
      if (lookahead == 'a') ADVANCE(55);
      if (lookahead == 'I' ||
          lookahead == 'N') ADVANCE(110);
      if (lookahead == 'i' ||
          lookahead == 'n') ADVANCE(108);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(113);
      END_STATE();
    case 5:
      if (lookahead == 'B') ADVANCE(119);
      if (lookahead == 'C') ADVANCE(115);
      if (lookahead == 'I') ADVANCE(121);
      if (lookahead == 'N') ADVANCE(116);
      if (lookahead == 'S') ADVANCE(124);
      if (lookahead == 'n') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(127);
      END_STATE();
    case 6:
      if (lookahead == 'N') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'S') ADVANCE(65);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(60);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(38);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(37);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(74);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(64);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(91);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 26:
      if (lookahead == 'g') ADVANCE(6);
      END_STATE();
    case 27:
      if (lookahead == 'g') ADVANCE(105);
      END_STATE();
    case 28:
      if (lookahead == 'g') ADVANCE(104);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(47);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 33:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(89);
      END_STATE();
    case 40:
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(63);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(61);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 54:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 55:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 56:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 57:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(107);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(92);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(33);
      if (lookahead == 'u') ADVANCE(39);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 66:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 67:
      if (lookahead == 'u') ADVANCE(50);
      END_STATE();
    case 68:
      if (lookahead == 'y') ADVANCE(87);
      END_STATE();
    case 69:
      if (lookahead == 'I' ||
          lookahead == 'N' ||
          lookahead == 'i' ||
          lookahead == 'n') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 70:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(70);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(127);
      END_STATE();
    case 71:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(71);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(113);
      END_STATE();
    case 72:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_public);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_declare);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_entity);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_assert);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_assert);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(98);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(100);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_Int);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_Nat);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_CString);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_String);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_BigNat);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_num_lit);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_num_lit);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(112);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_num_lit);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(113);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_num_lit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_enum_tok);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_enum_tok);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'N') ADVANCE(11);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'S') ADVANCE(65);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'a') ADVANCE(126);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'g') ADVANCE(114);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'g') ADVANCE(106);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'i') ADVANCE(117);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'i') ADVANCE(122);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'n') ADVANCE(125);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'n') ADVANCE(118);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'r') ADVANCE(120);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 't') ADVANCE(123);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 't') ADVANCE(102);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 't') ADVANCE(103);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 5},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 70},
  [99] = {.lex_state = 71},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_public] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_declare] = ACTIONS(1),
    [anon_sym_entity] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_assert] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_CString] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [anon_sym_BigNat] = ACTIONS(1),
    [sym_num_lit] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(106),
    [sym__components] = STATE(34),
    [sym__function_def] = STATE(35),
    [sym__namespace_def] = STATE(36),
    [sym__entity] = STATE(37),
    [sym__enum] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_public] = ACTIONS(5),
    [anon_sym_function] = ACTIONS(7),
    [anon_sym_declare] = ACTIONS(9),
    [anon_sym_entity] = ACTIONS(11),
    [anon_sym_enum] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(15), 1,
      anon_sym_return,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_assert,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_num_lit,
    ACTIONS(25), 1,
      sym_enum_tok,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(3), 1,
      aux_sym__statement_block_repeat1,
    STATE(7), 1,
      sym__enum_access,
    STATE(21), 1,
      sym__definition,
    STATE(100), 1,
      sym__return,
    STATE(107), 1,
      sym__bind_id_to_type,
    STATE(19), 2,
      sym__statement,
      sym__assertion,
  [41] = 13,
    ACTIONS(15), 1,
      anon_sym_return,
    ACTIONS(19), 1,
      anon_sym_assert,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      sym_num_lit,
    ACTIONS(25), 1,
      sym_enum_tok,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym__statement_block_repeat1,
    STATE(7), 1,
      sym__enum_access,
    STATE(21), 1,
      sym__definition,
    STATE(102), 1,
      sym__return,
    STATE(107), 1,
      sym__bind_id_to_type,
    STATE(19), 2,
      sym__statement,
      sym__assertion,
  [82] = 12,
    ACTIONS(31), 1,
      anon_sym_return,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 1,
      anon_sym_assert,
    ACTIONS(38), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      sym_num_lit,
    ACTIONS(44), 1,
      sym_enum_tok,
    ACTIONS(47), 1,
      sym_identifier,
    STATE(4), 1,
      aux_sym__statement_block_repeat1,
    STATE(7), 1,
      sym__enum_access,
    STATE(21), 1,
      sym__definition,
    STATE(107), 1,
      sym__bind_id_to_type,
    STATE(19), 2,
      sym__statement,
      sym__assertion,
  [120] = 12,
    ACTIONS(5), 1,
      anon_sym_public,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_declare,
    ACTIONS(11), 1,
      anon_sym_entity,
    ACTIONS(13), 1,
      anon_sym_enum,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(34), 1,
      sym__components,
    STATE(35), 1,
      sym__function_def,
    STATE(36), 1,
      sym__namespace_def,
    STATE(37), 1,
      sym__entity,
    STATE(38), 1,
      sym__enum,
  [157] = 12,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(54), 1,
      anon_sym_public,
    ACTIONS(57), 1,
      anon_sym_function,
    ACTIONS(60), 1,
      anon_sym_declare,
    ACTIONS(63), 1,
      anon_sym_entity,
    ACTIONS(66), 1,
      anon_sym_enum,
    STATE(6), 1,
      aux_sym_source_file_repeat1,
    STATE(34), 1,
      sym__components,
    STATE(35), 1,
      sym__function_def,
    STATE(36), 1,
      sym__namespace_def,
    STATE(37), 1,
      sym__entity,
    STATE(38), 1,
      sym__enum,
  [194] = 2,
    ACTIONS(71), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(69), 6,
      anon_sym_return,
      anon_sym_assert,
      anon_sym_let,
      sym_num_lit,
      sym_enum_tok,
      sym_identifier,
  [207] = 3,
    ACTIONS(73), 1,
      sym_num_lit,
    ACTIONS(75), 1,
      sym_identifier,
    STATE(68), 6,
      sym__accessor,
      sym__value,
      sym__expression,
      sym__less_than,
      sym__greater_than,
      sym__addition,
  [222] = 3,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(77), 1,
      sym_num_lit,
    STATE(82), 6,
      sym__accessor,
      sym__value,
      sym__expression,
      sym__less_than,
      sym__greater_than,
      sym__addition,
  [237] = 3,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(79), 1,
      sym_num_lit,
    STATE(77), 6,
      sym__accessor,
      sym__value,
      sym__expression,
      sym__less_than,
      sym__greater_than,
      sym__addition,
  [252] = 3,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(81), 1,
      sym_num_lit,
    STATE(76), 6,
      sym__accessor,
      sym__value,
      sym__expression,
      sym__less_than,
      sym__greater_than,
      sym__addition,
  [267] = 2,
    ACTIONS(85), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(83), 6,
      anon_sym_return,
      anon_sym_assert,
      anon_sym_let,
      sym_num_lit,
      sym_enum_tok,
      sym_identifier,
  [280] = 2,
    ACTIONS(89), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(87), 6,
      anon_sym_return,
      anon_sym_assert,
      anon_sym_let,
      sym_num_lit,
      sym_enum_tok,
      sym_identifier,
  [293] = 3,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(91), 1,
      sym_num_lit,
    STATE(83), 6,
      sym__accessor,
      sym__value,
      sym__expression,
      sym__less_than,
      sym__greater_than,
      sym__addition,
  [308] = 3,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(93), 1,
      sym_num_lit,
    STATE(84), 6,
      sym__accessor,
      sym__value,
      sym__expression,
      sym__less_than,
      sym__greater_than,
      sym__addition,
  [323] = 3,
    STATE(85), 1,
      sym__type,
    ACTIONS(97), 2,
      anon_sym_CString,
      anon_sym_BigNat,
    ACTIONS(95), 4,
      anon_sym_Int,
      anon_sym_Nat,
      anon_sym_String,
      sym_namespace_tok,
  [337] = 3,
    STATE(47), 1,
      sym__type,
    ACTIONS(101), 2,
      anon_sym_CString,
      anon_sym_BigNat,
    ACTIONS(99), 4,
      anon_sym_Int,
      anon_sym_Nat,
      anon_sym_String,
      sym_namespace_tok,
  [351] = 6,
    ACTIONS(25), 1,
      sym_enum_tok,
    ACTIONS(103), 1,
      anon_sym_SEMI,
    ACTIONS(105), 1,
      anon_sym_assert,
    ACTIONS(107), 1,
      sym_num_lit,
    STATE(7), 1,
      sym__enum_access,
    STATE(104), 2,
      sym__statement,
      sym__assertion,
  [371] = 2,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    ACTIONS(109), 6,
      anon_sym_return,
      anon_sym_assert,
      anon_sym_let,
      sym_num_lit,
      sym_enum_tok,
      sym_identifier,
  [383] = 3,
    STATE(65), 1,
      sym__type,
    ACTIONS(115), 2,
      anon_sym_CString,
      anon_sym_BigNat,
    ACTIONS(113), 4,
      anon_sym_Int,
      anon_sym_Nat,
      anon_sym_String,
      sym_namespace_tok,
  [397] = 2,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    ACTIONS(117), 6,
      anon_sym_return,
      anon_sym_assert,
      anon_sym_let,
      sym_num_lit,
      sym_enum_tok,
      sym_identifier,
  [409] = 6,
    ACTIONS(123), 1,
      anon_sym_DOT,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(127), 1,
      anon_sym_GT_EQ,
    ACTIONS(129), 1,
      anon_sym_LT,
    ACTIONS(131), 1,
      anon_sym_LT_EQ,
    ACTIONS(121), 2,
      anon_sym_SEMI,
      anon_sym_PLUS,
  [429] = 2,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    ACTIONS(133), 6,
      anon_sym_return,
      anon_sym_assert,
      anon_sym_let,
      sym_num_lit,
      sym_enum_tok,
      sym_identifier,
  [441] = 2,
    ACTIONS(139), 1,
      anon_sym_RBRACE,
    ACTIONS(137), 6,
      anon_sym_return,
      anon_sym_assert,
      anon_sym_let,
      sym_num_lit,
      sym_enum_tok,
      sym_identifier,
  [453] = 2,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    ACTIONS(141), 6,
      anon_sym_return,
      anon_sym_assert,
      anon_sym_let,
      sym_num_lit,
      sym_enum_tok,
      sym_identifier,
  [465] = 2,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    ACTIONS(145), 6,
      anon_sym_return,
      anon_sym_assert,
      anon_sym_let,
      sym_num_lit,
      sym_enum_tok,
      sym_identifier,
  [477] = 1,
    ACTIONS(149), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [486] = 1,
    ACTIONS(151), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [495] = 1,
    ACTIONS(153), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [504] = 1,
    ACTIONS(155), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [513] = 1,
    ACTIONS(157), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [522] = 1,
    ACTIONS(159), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [531] = 1,
    ACTIONS(161), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [540] = 1,
    ACTIONS(163), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [549] = 1,
    ACTIONS(165), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [558] = 1,
    ACTIONS(167), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [567] = 1,
    ACTIONS(169), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [576] = 1,
    ACTIONS(171), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [585] = 1,
    ACTIONS(173), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [594] = 1,
    ACTIONS(175), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [603] = 1,
    ACTIONS(177), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [612] = 1,
    ACTIONS(179), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [621] = 1,
    ACTIONS(181), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [630] = 1,
    ACTIONS(183), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [639] = 1,
    ACTIONS(185), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [648] = 1,
    ACTIONS(187), 6,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
      anon_sym_enum,
  [657] = 1,
    ACTIONS(189), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
  [665] = 4,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(49), 1,
      aux_sym__parameters_repeat1,
    STATE(59), 1,
      sym__bind_id_to_type,
  [678] = 4,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(49), 1,
      aux_sym__parameters_repeat1,
    STATE(59), 1,
      sym__bind_id_to_type,
  [691] = 3,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    ACTIONS(202), 1,
      sym_identifier,
    STATE(51), 2,
      sym__enum_value,
      aux_sym__enum_block_repeat1,
  [702] = 3,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    ACTIONS(206), 1,
      sym_identifier,
    STATE(51), 2,
      sym__enum_value,
      aux_sym__enum_block_repeat1,
  [713] = 4,
    ACTIONS(209), 1,
      anon_sym_RBRACE,
    ACTIONS(211), 1,
      anon_sym_field,
    STATE(53), 1,
      aux_sym__field_block_repeat1,
    STATE(75), 1,
      sym__field,
  [726] = 4,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    ACTIONS(215), 1,
      anon_sym_field,
    STATE(53), 1,
      aux_sym__field_block_repeat1,
    STATE(75), 1,
      sym__field,
  [739] = 4,
    ACTIONS(193), 1,
      sym_identifier,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym__parameters_repeat1,
    STATE(59), 1,
      sym__bind_id_to_type,
  [752] = 4,
    ACTIONS(211), 1,
      anon_sym_field,
    ACTIONS(220), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      aux_sym__field_block_repeat1,
    STATE(75), 1,
      sym__field,
  [765] = 3,
    ACTIONS(202), 1,
      sym_identifier,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    STATE(50), 2,
      sym__enum_value,
      aux_sym__enum_block_repeat1,
  [776] = 2,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    ACTIONS(226), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [784] = 3,
    ACTIONS(228), 1,
      anon_sym_COLON,
    ACTIONS(230), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym__statement_block,
  [794] = 2,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    ACTIONS(234), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [802] = 3,
    ACTIONS(230), 1,
      anon_sym_LBRACE,
    ACTIONS(236), 1,
      anon_sym_COLON,
    STATE(29), 1,
      sym__statement_block,
  [812] = 1,
    ACTIONS(238), 2,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [817] = 1,
    ACTIONS(240), 2,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [822] = 2,
    ACTIONS(242), 1,
      sym_identifier,
    STATE(96), 1,
      sym__bind_id_to_type,
  [829] = 1,
    ACTIONS(244), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [834] = 2,
    ACTIONS(230), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym__statement_block,
  [841] = 2,
    ACTIONS(246), 1,
      anon_sym_COLON,
    ACTIONS(248), 1,
      anon_sym_EQ,
  [848] = 2,
    ACTIONS(250), 1,
      anon_sym_LPAREN,
    STATE(60), 1,
      sym__parameters,
  [855] = 2,
    ACTIONS(252), 1,
      anon_sym_SEMI,
    ACTIONS(254), 1,
      anon_sym_PLUS,
  [862] = 2,
    ACTIONS(246), 1,
      anon_sym_COLON,
    ACTIONS(256), 1,
      anon_sym_EQ,
  [869] = 2,
    ACTIONS(258), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym__field_block,
  [876] = 2,
    ACTIONS(260), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      sym__enum_block,
  [883] = 1,
    ACTIONS(262), 2,
      anon_sym_RBRACE,
      anon_sym_field,
  [888] = 2,
    ACTIONS(250), 1,
      anon_sym_LPAREN,
    STATE(58), 1,
      sym__parameters,
  [895] = 2,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(86), 1,
      sym__bind_id_to_type,
  [902] = 1,
    ACTIONS(264), 2,
      anon_sym_RBRACE,
      anon_sym_field,
  [907] = 2,
    ACTIONS(254), 1,
      anon_sym_PLUS,
    ACTIONS(266), 1,
      anon_sym_SEMI,
  [914] = 2,
    ACTIONS(254), 1,
      anon_sym_PLUS,
    ACTIONS(268), 1,
      anon_sym_SEMI,
  [921] = 1,
    ACTIONS(270), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [926] = 1,
    ACTIONS(272), 2,
      anon_sym_SEMI,
      anon_sym_PLUS,
  [931] = 1,
    ACTIONS(274), 2,
      anon_sym_SEMI,
      anon_sym_PLUS,
  [936] = 1,
    ACTIONS(276), 2,
      anon_sym_SEMI,
      anon_sym_PLUS,
  [941] = 1,
    ACTIONS(278), 2,
      anon_sym_SEMI,
      anon_sym_PLUS,
  [946] = 2,
    ACTIONS(254), 1,
      anon_sym_PLUS,
    ACTIONS(280), 1,
      anon_sym_SEMI,
  [953] = 2,
    ACTIONS(254), 1,
      anon_sym_PLUS,
    ACTIONS(282), 1,
      anon_sym_SEMI,
  [960] = 2,
    ACTIONS(230), 1,
      anon_sym_LBRACE,
    STATE(42), 1,
      sym__statement_block,
  [967] = 1,
    ACTIONS(284), 1,
      anon_sym_SEMI,
  [971] = 1,
    ACTIONS(286), 1,
      anon_sym_RBRACE,
  [975] = 1,
    ACTIONS(288), 1,
      sym_identifier,
  [979] = 1,
    ACTIONS(290), 1,
      sym_identifier,
  [983] = 1,
    ACTIONS(292), 1,
      sym_identifier,
  [987] = 1,
    ACTIONS(294), 1,
      sym_identifier,
  [991] = 1,
    ACTIONS(296), 1,
      anon_sym_POUND,
  [995] = 1,
    ACTIONS(246), 1,
      anon_sym_COLON,
  [999] = 1,
    ACTIONS(298), 1,
      anon_sym_namespace,
  [1003] = 1,
    ACTIONS(300), 1,
      anon_sym_SEMI,
  [1007] = 1,
    ACTIONS(302), 1,
      anon_sym_EQ,
  [1011] = 1,
    ACTIONS(304), 1,
      sym_identifier,
  [1015] = 1,
    ACTIONS(306), 1,
      sym_namespace_tok,
  [1019] = 1,
    ACTIONS(308), 1,
      sym_enum_tok,
  [1023] = 1,
    ACTIONS(310), 1,
      anon_sym_RBRACE,
  [1027] = 1,
    ACTIONS(312), 1,
      sym_identifier,
  [1031] = 1,
    ACTIONS(314), 1,
      anon_sym_RBRACE,
  [1035] = 1,
    ACTIONS(316), 1,
      anon_sym_RBRACE,
  [1039] = 1,
    ACTIONS(318), 1,
      anon_sym_SEMI,
  [1043] = 1,
    ACTIONS(320), 1,
      anon_sym_function,
  [1047] = 1,
    ACTIONS(322), 1,
      ts_builtin_sym_end,
  [1051] = 1,
    ACTIONS(324), 1,
      anon_sym_EQ,
  [1055] = 1,
    ACTIONS(326), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 157,
  [SMALL_STATE(7)] = 194,
  [SMALL_STATE(8)] = 207,
  [SMALL_STATE(9)] = 222,
  [SMALL_STATE(10)] = 237,
  [SMALL_STATE(11)] = 252,
  [SMALL_STATE(12)] = 267,
  [SMALL_STATE(13)] = 280,
  [SMALL_STATE(14)] = 293,
  [SMALL_STATE(15)] = 308,
  [SMALL_STATE(16)] = 323,
  [SMALL_STATE(17)] = 337,
  [SMALL_STATE(18)] = 351,
  [SMALL_STATE(19)] = 371,
  [SMALL_STATE(20)] = 383,
  [SMALL_STATE(21)] = 397,
  [SMALL_STATE(22)] = 409,
  [SMALL_STATE(23)] = 429,
  [SMALL_STATE(24)] = 441,
  [SMALL_STATE(25)] = 453,
  [SMALL_STATE(26)] = 465,
  [SMALL_STATE(27)] = 477,
  [SMALL_STATE(28)] = 486,
  [SMALL_STATE(29)] = 495,
  [SMALL_STATE(30)] = 504,
  [SMALL_STATE(31)] = 513,
  [SMALL_STATE(32)] = 522,
  [SMALL_STATE(33)] = 531,
  [SMALL_STATE(34)] = 540,
  [SMALL_STATE(35)] = 549,
  [SMALL_STATE(36)] = 558,
  [SMALL_STATE(37)] = 567,
  [SMALL_STATE(38)] = 576,
  [SMALL_STATE(39)] = 585,
  [SMALL_STATE(40)] = 594,
  [SMALL_STATE(41)] = 603,
  [SMALL_STATE(42)] = 612,
  [SMALL_STATE(43)] = 621,
  [SMALL_STATE(44)] = 630,
  [SMALL_STATE(45)] = 639,
  [SMALL_STATE(46)] = 648,
  [SMALL_STATE(47)] = 657,
  [SMALL_STATE(48)] = 665,
  [SMALL_STATE(49)] = 678,
  [SMALL_STATE(50)] = 691,
  [SMALL_STATE(51)] = 702,
  [SMALL_STATE(52)] = 713,
  [SMALL_STATE(53)] = 726,
  [SMALL_STATE(54)] = 739,
  [SMALL_STATE(55)] = 752,
  [SMALL_STATE(56)] = 765,
  [SMALL_STATE(57)] = 776,
  [SMALL_STATE(58)] = 784,
  [SMALL_STATE(59)] = 794,
  [SMALL_STATE(60)] = 802,
  [SMALL_STATE(61)] = 812,
  [SMALL_STATE(62)] = 817,
  [SMALL_STATE(63)] = 822,
  [SMALL_STATE(64)] = 829,
  [SMALL_STATE(65)] = 834,
  [SMALL_STATE(66)] = 841,
  [SMALL_STATE(67)] = 848,
  [SMALL_STATE(68)] = 855,
  [SMALL_STATE(69)] = 862,
  [SMALL_STATE(70)] = 869,
  [SMALL_STATE(71)] = 876,
  [SMALL_STATE(72)] = 883,
  [SMALL_STATE(73)] = 888,
  [SMALL_STATE(74)] = 895,
  [SMALL_STATE(75)] = 902,
  [SMALL_STATE(76)] = 907,
  [SMALL_STATE(77)] = 914,
  [SMALL_STATE(78)] = 921,
  [SMALL_STATE(79)] = 926,
  [SMALL_STATE(80)] = 931,
  [SMALL_STATE(81)] = 936,
  [SMALL_STATE(82)] = 941,
  [SMALL_STATE(83)] = 946,
  [SMALL_STATE(84)] = 953,
  [SMALL_STATE(85)] = 960,
  [SMALL_STATE(86)] = 967,
  [SMALL_STATE(87)] = 971,
  [SMALL_STATE(88)] = 975,
  [SMALL_STATE(89)] = 979,
  [SMALL_STATE(90)] = 983,
  [SMALL_STATE(91)] = 987,
  [SMALL_STATE(92)] = 991,
  [SMALL_STATE(93)] = 995,
  [SMALL_STATE(94)] = 999,
  [SMALL_STATE(95)] = 1003,
  [SMALL_STATE(96)] = 1007,
  [SMALL_STATE(97)] = 1011,
  [SMALL_STATE(98)] = 1015,
  [SMALL_STATE(99)] = 1019,
  [SMALL_STATE(100)] = 1023,
  [SMALL_STATE(101)] = 1027,
  [SMALL_STATE(102)] = 1031,
  [SMALL_STATE(103)] = 1035,
  [SMALL_STATE(104)] = 1039,
  [SMALL_STATE(105)] = 1043,
  [SMALL_STATE(106)] = 1047,
  [SMALL_STATE(107)] = 1051,
  [SMALL_STATE(108)] = 1055,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__statement_block_repeat1, 2, 0, 23),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_block_repeat1, 2, 0, 23),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_block_repeat1, 2, 0, 23), SHIFT_REPEAT(8),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_block_repeat1, 2, 0, 23), SHIFT_REPEAT(63),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_block_repeat1, 2, 0, 23), SHIFT_REPEAT(19),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_block_repeat1, 2, 0, 23), SHIFT_REPEAT(92),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_block_repeat1, 2, 0, 23), SHIFT_REPEAT(66),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 6),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 6), SHIFT_REPEAT(105),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 6), SHIFT_REPEAT(91),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 6), SHIFT_REPEAT(94),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 6), SHIFT_REPEAT(101),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 6), SHIFT_REPEAT(99),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 16),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 16),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__assertion, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assertion, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__enum_access, 3, 0, 26),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__enum_access, 3, 0, 26),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__statement_block_repeat1, 1, 0, 16),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_block_repeat1, 1, 0, 16),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__statement_block_repeat1, 1, 0, 9),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_block_repeat1, 1, 0, 9),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__definition, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__definition, 4, 0, 9),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 4, 0, 9),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__definition, 5, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 5, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__definition, 5, 0, 14),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 5, 0, 14),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__enum, 3, 0, 8),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_def, 4, 0, 10),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__namespace_def, 4, 0, 11),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_block, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__enum_block, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_def, 5, 0, 13),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__components, 1, 0, 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__components, 1, 0, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__components, 1, 0, 4),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__components, 1, 0, 5),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_block, 3, 0, 17),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__enum_block, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 4, 0, 27),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_def, 6, 0, 20),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 3, 0, 21),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 3, 0, 22),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_def, 7, 0, 25),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entity, 3, 0, 7),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bind_id_to_type, 3, 0, 19),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 15),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 15), SHIFT_REPEAT(93),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__enum_block_repeat1, 2, 0, 0),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__enum_block_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 2, 0, 18),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 2, 0, 18), SHIFT_REPEAT(74),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__enum_value, 1, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 1, 0, 9),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 3, 0, 14),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__enum_value, 2, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field, 3, 0, 24),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 1, 0, 12),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 9),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__accessor, 3, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__less_than, 3, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__greater_than, 3, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__addition, 3, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__return, 3, 0, 21),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__return, 2, 0, 0),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [322] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bosque(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bosque",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
