/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 94
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 21
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_public = 1,
  anon_sym_function = 2,
  anon_sym_COLON = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_return = 7,
  anon_sym_SEMI = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_declare = 11,
  anon_sym_namespace = 12,
  anon_sym_entity = 13,
  anon_sym_assert = 14,
  anon_sym_field = 15,
  anon_sym_let = 16,
  anon_sym_EQ = 17,
  anon_sym_GT = 18,
  anon_sym_GT_EQ = 19,
  anon_sym_LT = 20,
  anon_sym_LT_EQ = 21,
  anon_sym_PLUS = 22,
  anon_sym_Int = 23,
  anon_sym_Nat = 24,
  anon_sym_CString = 25,
  anon_sym_String = 26,
  sym_namespace_tok = 27,
  sym_identifier = 28,
  sym_source_file = 29,
  sym__components = 30,
  sym__function_def = 31,
  sym__parameters = 32,
  sym__return = 33,
  sym__statement_block = 34,
  sym__namespace_def = 35,
  sym__entity = 36,
  sym__field_block = 37,
  sym__assertion = 38,
  sym__field = 39,
  sym__definition = 40,
  sym__expression = 41,
  sym__less_than = 42,
  sym__greater_than = 43,
  sym__addition = 44,
  sym__bind_id_to_type = 45,
  sym__type = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym__parameters_repeat1 = 48,
  aux_sym__statement_block_repeat1 = 49,
  aux_sym__field_block_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_public] = "public",
  [anon_sym_function] = "function",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_return] = "return",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_declare] = "declare",
  [anon_sym_namespace] = "namespace",
  [anon_sym_entity] = "entity",
  [anon_sym_assert] = "assert",
  [anon_sym_field] = "field",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_PLUS] = "+",
  [anon_sym_Int] = "Int",
  [anon_sym_Nat] = "Nat",
  [anon_sym_CString] = "CString",
  [anon_sym_String] = "String",
  [sym_namespace_tok] = "namespace_tok",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__components] = "_components",
  [sym__function_def] = "_function_def",
  [sym__parameters] = "_parameters",
  [sym__return] = "_return",
  [sym__statement_block] = "_statement_block",
  [sym__namespace_def] = "_namespace_def",
  [sym__entity] = "_entity",
  [sym__field_block] = "_field_block",
  [sym__assertion] = "_assertion",
  [sym__field] = "_field",
  [sym__definition] = "_definition",
  [sym__expression] = "_expression",
  [sym__less_than] = "_less_than",
  [sym__greater_than] = "_greater_than",
  [sym__addition] = "_addition",
  [sym__bind_id_to_type] = "_bind_id_to_type",
  [sym__type] = "_type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__parameters_repeat1] = "_parameters_repeat1",
  [aux_sym__statement_block_repeat1] = "_statement_block_repeat1",
  [aux_sym__field_block_repeat1] = "_field_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_public] = anon_sym_public,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_declare] = anon_sym_declare,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_entity] = anon_sym_entity,
  [anon_sym_assert] = anon_sym_assert,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_Int] = anon_sym_Int,
  [anon_sym_Nat] = anon_sym_Nat,
  [anon_sym_CString] = anon_sym_CString,
  [anon_sym_String] = anon_sym_String,
  [sym_namespace_tok] = sym_namespace_tok,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__components] = sym__components,
  [sym__function_def] = sym__function_def,
  [sym__parameters] = sym__parameters,
  [sym__return] = sym__return,
  [sym__statement_block] = sym__statement_block,
  [sym__namespace_def] = sym__namespace_def,
  [sym__entity] = sym__entity,
  [sym__field_block] = sym__field_block,
  [sym__assertion] = sym__assertion,
  [sym__field] = sym__field,
  [sym__definition] = sym__definition,
  [sym__expression] = sym__expression,
  [sym__less_than] = sym__less_than,
  [sym__greater_than] = sym__greater_than,
  [sym__addition] = sym__addition,
  [sym__bind_id_to_type] = sym__bind_id_to_type,
  [sym__type] = sym__type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__parameters_repeat1] = aux_sym__parameters_repeat1,
  [aux_sym__statement_block_repeat1] = aux_sym__statement_block_repeat1,
  [aux_sym__field_block_repeat1] = aux_sym__field_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_public] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_declare] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entity] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assert] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Nat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CString] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [sym_namespace_tok] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__components] = {
    .visible = false,
    .named = true,
  },
  [sym__function_def] = {
    .visible = false,
    .named = true,
  },
  [sym__parameters] = {
    .visible = false,
    .named = true,
  },
  [sym__return] = {
    .visible = false,
    .named = true,
  },
  [sym__statement_block] = {
    .visible = false,
    .named = true,
  },
  [sym__namespace_def] = {
    .visible = false,
    .named = true,
  },
  [sym__entity] = {
    .visible = false,
    .named = true,
  },
  [sym__field_block] = {
    .visible = false,
    .named = true,
  },
  [sym__assertion] = {
    .visible = false,
    .named = true,
  },
  [sym__field] = {
    .visible = false,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__less_than] = {
    .visible = false,
    .named = true,
  },
  [sym__greater_than] = {
    .visible = false,
    .named = true,
  },
  [sym__addition] = {
    .visible = false,
    .named = true,
  },
  [sym__bind_id_to_type] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__field_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bsq_prim = 1,
  field_entity_name = 2,
  field_field_block = 3,
  field_func_body = 4,
  field_func_name = 5,
  field_keyword = 6,
  field_namespace_id = 7,
  field_params = 8,
  field_return_type = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bsq_prim] = "bsq_prim",
  [field_entity_name] = "entity_name",
  [field_field_block] = "field_block",
  [field_func_body] = "func_body",
  [field_func_name] = "func_name",
  [field_keyword] = "keyword",
  [field_namespace_id] = "namespace_id",
  [field_params] = "params",
  [field_return_type] = "return_type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 9},
  [2] = {.index = 9, .length = 5},
  [3] = {.index = 14, .length = 1},
  [4] = {.index = 15, .length = 4},
  [5] = {.index = 19, .length = 18},
  [6] = {.index = 37, .length = 5},
  [7] = {.index = 42, .length = 1},
  [8] = {.index = 43, .length = 5},
  [9] = {.index = 48, .length = 1},
  [10] = {.index = 49, .length = 2},
  [11] = {.index = 51, .length = 5},
  [12] = {.index = 56, .length = 1},
  [13] = {.index = 57, .length = 2},
  [14] = {.index = 59, .length = 2},
  [15] = {.index = 61, .length = 4},
  [16] = {.index = 65, .length = 1},
  [17] = {.index = 66, .length = 7},
  [18] = {.index = 73, .length = 2},
  [19] = {.index = 75, .length = 7},
  [20] = {.index = 82, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_bsq_prim, 0, .inherited = true},
    {field_entity_name, 0, .inherited = true},
    {field_field_block, 0, .inherited = true},
    {field_func_body, 0, .inherited = true},
    {field_func_name, 0, .inherited = true},
    {field_keyword, 0, .inherited = true},
    {field_namespace_id, 0, .inherited = true},
    {field_params, 0, .inherited = true},
    {field_return_type, 0, .inherited = true},
  [9] =
    {field_bsq_prim, 0, .inherited = true},
    {field_func_body, 0, .inherited = true},
    {field_func_name, 0, .inherited = true},
    {field_params, 0, .inherited = true},
    {field_return_type, 0, .inherited = true},
  [14] =
    {field_namespace_id, 0, .inherited = true},
  [15] =
    {field_bsq_prim, 0, .inherited = true},
    {field_entity_name, 0, .inherited = true},
    {field_field_block, 0, .inherited = true},
    {field_keyword, 0, .inherited = true},
  [19] =
    {field_bsq_prim, 0, .inherited = true},
    {field_bsq_prim, 1, .inherited = true},
    {field_entity_name, 0, .inherited = true},
    {field_entity_name, 1, .inherited = true},
    {field_field_block, 0, .inherited = true},
    {field_field_block, 1, .inherited = true},
    {field_func_body, 0, .inherited = true},
    {field_func_body, 1, .inherited = true},
    {field_func_name, 0, .inherited = true},
    {field_func_name, 1, .inherited = true},
    {field_keyword, 0, .inherited = true},
    {field_keyword, 1, .inherited = true},
    {field_namespace_id, 0, .inherited = true},
    {field_namespace_id, 1, .inherited = true},
    {field_params, 0, .inherited = true},
    {field_params, 1, .inherited = true},
    {field_return_type, 0, .inherited = true},
    {field_return_type, 1, .inherited = true},
  [37] =
    {field_bsq_prim, 2, .inherited = true},
    {field_entity_name, 1},
    {field_field_block, 2},
    {field_keyword, 0},
    {field_keyword, 2, .inherited = true},
  [42] =
    {field_bsq_prim, 0, .inherited = true},
  [43] =
    {field_bsq_prim, 2, .inherited = true},
    {field_bsq_prim, 3, .inherited = true},
    {field_func_body, 3},
    {field_func_name, 1},
    {field_params, 2},
  [48] =
    {field_namespace_id, 2},
  [49] =
    {field_bsq_prim, 0, .inherited = true},
    {field_keyword, 0, .inherited = true},
  [51] =
    {field_bsq_prim, 3, .inherited = true},
    {field_bsq_prim, 4, .inherited = true},
    {field_func_body, 4},
    {field_func_name, 2},
    {field_params, 3},
  [56] =
    {field_bsq_prim, 1, .inherited = true},
  [57] =
    {field_bsq_prim, 0, .inherited = true},
    {field_bsq_prim, 1, .inherited = true},
  [59] =
    {field_bsq_prim, 1, .inherited = true},
    {field_keyword, 1, .inherited = true},
  [61] =
    {field_bsq_prim, 0, .inherited = true},
    {field_bsq_prim, 1, .inherited = true},
    {field_keyword, 0, .inherited = true},
    {field_keyword, 1, .inherited = true},
  [65] =
    {field_bsq_prim, 2},
  [66] =
    {field_bsq_prim, 2, .inherited = true},
    {field_bsq_prim, 4},
    {field_bsq_prim, 5, .inherited = true},
    {field_func_body, 5},
    {field_func_name, 1},
    {field_params, 2},
    {field_return_type, 3},
  [73] =
    {field_bsq_prim, 1, .inherited = true},
    {field_keyword, 0},
  [75] =
    {field_bsq_prim, 3, .inherited = true},
    {field_bsq_prim, 5},
    {field_bsq_prim, 6, .inherited = true},
    {field_func_body, 6},
    {field_func_name, 2},
    {field_params, 3},
    {field_return_type, 4},
  [82] =
    {field_bsq_prim, 2, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(54);
      ADVANCE_MAP(
        '(', 58,
        ')', 60,
        '+', 77,
        ',', 59,
        ':', 57,
        ';', 62,
        '<', 75,
        '=', 72,
        '>', 73,
        'C', 82,
        'I', 87,
        'N', 83,
        'S', 89,
        'a', 42,
        'd', 12,
        'e', 33,
        'f', 22,
        'l', 18,
        'n', 3,
        'p', 51,
        'r', 19,
        '{', 63,
        '}', 64,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(92);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(60);
      if (lookahead == ',') ADVANCE(59);
      if (lookahead == ';') ADVANCE(62);
      if (lookahead == '=') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(92);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 2:
      if (lookahead == ';') ADVANCE(62);
      if (lookahead == 'l') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(50);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(80);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(47);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 29:
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(61);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 36:
      if (lookahead == 'p') ADVANCE(4);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(43);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(70);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 52:
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 53:
      if (lookahead == 'y') ADVANCE(67);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_public);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_declare);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_entity);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_assert);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_let);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_Int);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_Nat);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_CString);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_String);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'S') ADVANCE(44);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'a') ADVANCE(91);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'g') ADVANCE(81);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'i') ADVANCE(86);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'n') ADVANCE(84);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'n') ADVANCE(90);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 'r') ADVANCE(85);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 't') ADVANCE(88);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 't') ADVANCE(78);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (lookahead == 't') ADVANCE(79);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(94);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(71);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_public] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_declare] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_entity] = ACTIONS(1),
    [anon_sym_assert] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_Int] = ACTIONS(1),
    [anon_sym_Nat] = ACTIONS(1),
    [anon_sym_CString] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [sym_namespace_tok] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(75),
    [sym__components] = STATE(9),
    [sym__function_def] = STATE(16),
    [sym__namespace_def] = STATE(18),
    [sym__entity] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_public] = ACTIONS(5),
    [anon_sym_function] = ACTIONS(7),
    [anon_sym_declare] = ACTIONS(9),
    [anon_sym_entity] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(5), 1,
      anon_sym_public,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_declare,
    ACTIONS(11), 1,
      anon_sym_entity,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(9), 1,
      sym__components,
    STATE(10), 1,
      sym__entity,
    STATE(16), 1,
      sym__function_def,
    STATE(18), 1,
      sym__namespace_def,
  [31] = 10,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_public,
    ACTIONS(20), 1,
      anon_sym_function,
    ACTIONS(23), 1,
      anon_sym_declare,
    ACTIONS(26), 1,
      anon_sym_entity,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(9), 1,
      sym__components,
    STATE(10), 1,
      sym__entity,
    STATE(16), 1,
      sym__function_def,
    STATE(18), 1,
      sym__namespace_def,
  [62] = 3,
    ACTIONS(31), 1,
      anon_sym_CString,
    STATE(56), 1,
      sym__type,
    ACTIONS(29), 4,
      anon_sym_Int,
      anon_sym_Nat,
      anon_sym_String,
      sym_namespace_tok,
  [75] = 6,
    ACTIONS(33), 1,
      anon_sym_return,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    ACTIONS(37), 1,
      anon_sym_assert,
    STATE(8), 1,
      aux_sym__statement_block_repeat1,
    STATE(42), 1,
      sym__assertion,
    STATE(79), 1,
      sym__return,
  [94] = 3,
    ACTIONS(41), 1,
      anon_sym_CString,
    STATE(49), 1,
      sym__type,
    ACTIONS(39), 4,
      anon_sym_Int,
      anon_sym_Nat,
      anon_sym_String,
      sym_namespace_tok,
  [107] = 3,
    ACTIONS(45), 1,
      anon_sym_CString,
    STATE(20), 1,
      sym__type,
    ACTIONS(43), 4,
      anon_sym_Int,
      anon_sym_Nat,
      anon_sym_String,
      sym_namespace_tok,
  [120] = 6,
    ACTIONS(33), 1,
      anon_sym_return,
    ACTIONS(37), 1,
      anon_sym_assert,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym__statement_block_repeat1,
    STATE(42), 1,
      sym__assertion,
    STATE(80), 1,
      sym__return,
  [139] = 1,
    ACTIONS(49), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [147] = 1,
    ACTIONS(51), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [155] = 1,
    ACTIONS(53), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [163] = 1,
    ACTIONS(55), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [171] = 1,
    ACTIONS(57), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [179] = 1,
    ACTIONS(59), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [187] = 1,
    ACTIONS(61), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [195] = 1,
    ACTIONS(63), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [203] = 1,
    ACTIONS(65), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [211] = 1,
    ACTIONS(67), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [219] = 1,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [227] = 1,
    ACTIONS(71), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
  [235] = 1,
    ACTIONS(73), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [243] = 5,
    ACTIONS(75), 1,
      anon_sym_SEMI,
    ACTIONS(77), 1,
      anon_sym_GT,
    ACTIONS(79), 1,
      anon_sym_GT_EQ,
    ACTIONS(81), 1,
      anon_sym_LT,
    ACTIONS(83), 1,
      anon_sym_LT_EQ,
  [259] = 1,
    ACTIONS(85), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [267] = 1,
    ACTIONS(87), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [275] = 4,
    ACTIONS(91), 1,
      anon_sym_assert,
    STATE(25), 1,
      aux_sym__statement_block_repeat1,
    STATE(42), 1,
      sym__assertion,
    ACTIONS(89), 2,
      anon_sym_return,
      anon_sym_RBRACE,
  [289] = 1,
    ACTIONS(94), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [297] = 1,
    ACTIONS(96), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [305] = 3,
    ACTIONS(98), 1,
      anon_sym_SEMI,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(65), 3,
      sym__expression,
      sym__less_than,
      sym__greater_than,
  [317] = 4,
    ACTIONS(102), 1,
      anon_sym_RPAREN,
    ACTIONS(104), 1,
      sym_identifier,
    STATE(30), 1,
      aux_sym__parameters_repeat1,
    STATE(39), 1,
      sym__bind_id_to_type,
  [330] = 4,
    ACTIONS(106), 1,
      anon_sym_RPAREN,
    ACTIONS(108), 1,
      sym_identifier,
    STATE(30), 1,
      aux_sym__parameters_repeat1,
    STATE(39), 1,
      sym__bind_id_to_type,
  [343] = 4,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    ACTIONS(113), 1,
      anon_sym_field,
    STATE(34), 1,
      aux_sym__field_block_repeat1,
    STATE(50), 1,
      sym__field,
  [356] = 4,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    ACTIONS(117), 1,
      anon_sym_field,
    STATE(32), 1,
      aux_sym__field_block_repeat1,
    STATE(50), 1,
      sym__field,
  [369] = 4,
    ACTIONS(104), 1,
      sym_identifier,
    ACTIONS(120), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym__parameters_repeat1,
    STATE(39), 1,
      sym__bind_id_to_type,
  [382] = 4,
    ACTIONS(113), 1,
      anon_sym_field,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__field_block_repeat1,
    STATE(50), 1,
      sym__field,
  [395] = 4,
    ACTIONS(124), 1,
      anon_sym_let,
    ACTIONS(126), 1,
      sym_identifier,
    STATE(71), 1,
      sym__definition,
    STATE(72), 1,
      sym__bind_id_to_type,
  [408] = 4,
    ACTIONS(77), 1,
      anon_sym_GT,
    ACTIONS(79), 1,
      anon_sym_GT_EQ,
    ACTIONS(81), 1,
      anon_sym_LT,
    ACTIONS(83), 1,
      anon_sym_LT_EQ,
  [421] = 2,
    ACTIONS(128), 1,
      sym_identifier,
    STATE(35), 3,
      sym__expression,
      sym__less_than,
      sym__greater_than,
  [430] = 3,
    ACTIONS(130), 1,
      anon_sym_COLON,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym__statement_block,
  [440] = 2,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(136), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [448] = 3,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    ACTIONS(138), 1,
      anon_sym_COLON,
    STATE(12), 1,
      sym__statement_block,
  [458] = 1,
    ACTIONS(140), 3,
      anon_sym_return,
      anon_sym_RBRACE,
      anon_sym_assert,
  [464] = 1,
    ACTIONS(142), 3,
      anon_sym_return,
      anon_sym_RBRACE,
      anon_sym_assert,
  [470] = 2,
    ACTIONS(144), 1,
      anon_sym_SEMI,
    ACTIONS(146), 2,
      anon_sym_let,
      sym_identifier,
  [478] = 2,
    ACTIONS(148), 1,
      anon_sym_SEMI,
    ACTIONS(150), 2,
      anon_sym_let,
      sym_identifier,
  [486] = 2,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    STATE(38), 1,
      sym__parameters,
  [493] = 2,
    ACTIONS(154), 1,
      sym_identifier,
    STATE(87), 1,
      sym__addition,
  [500] = 2,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym__field_block,
  [507] = 2,
    ACTIONS(104), 1,
      sym_identifier,
    STATE(76), 1,
      sym__bind_id_to_type,
  [514] = 2,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym__statement_block,
  [521] = 1,
    ACTIONS(158), 2,
      anon_sym_RBRACE,
      anon_sym_field,
  [526] = 1,
    ACTIONS(160), 2,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [531] = 1,
    ACTIONS(162), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [536] = 1,
    ACTIONS(164), 2,
      anon_sym_COLON,
      anon_sym_LBRACE,
  [541] = 2,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    STATE(40), 1,
      sym__parameters,
  [548] = 1,
    ACTIONS(166), 2,
      anon_sym_RBRACE,
      anon_sym_field,
  [553] = 2,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym__statement_block,
  [560] = 2,
    ACTIONS(168), 1,
      sym_identifier,
    STATE(77), 1,
      sym__bind_id_to_type,
  [567] = 2,
    ACTIONS(170), 1,
      anon_sym_COLON,
    ACTIONS(172), 1,
      anon_sym_EQ,
  [574] = 2,
    ACTIONS(170), 1,
      anon_sym_COLON,
    ACTIONS(174), 1,
      anon_sym_EQ,
  [581] = 2,
    ACTIONS(154), 1,
      sym_identifier,
    STATE(84), 1,
      sym__addition,
  [588] = 2,
    ACTIONS(154), 1,
      sym_identifier,
    STATE(85), 1,
      sym__addition,
  [595] = 2,
    ACTIONS(154), 1,
      sym_identifier,
    STATE(86), 1,
      sym__addition,
  [602] = 1,
    ACTIONS(176), 1,
      sym_identifier,
  [606] = 1,
    ACTIONS(178), 1,
      anon_sym_SEMI,
  [610] = 1,
    ACTIONS(75), 1,
      anon_sym_SEMI,
  [614] = 1,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
  [618] = 1,
    ACTIONS(182), 1,
      sym_identifier,
  [622] = 1,
    ACTIONS(184), 1,
      sym_identifier,
  [626] = 1,
    ACTIONS(186), 1,
      anon_sym_namespace,
  [630] = 1,
    ACTIONS(170), 1,
      anon_sym_COLON,
  [634] = 1,
    ACTIONS(188), 1,
      anon_sym_SEMI,
  [638] = 1,
    ACTIONS(190), 1,
      anon_sym_EQ,
  [642] = 1,
    ACTIONS(192), 1,
      sym_namespace_tok,
  [646] = 1,
    ACTIONS(194), 1,
      sym_namespace_tok,
  [650] = 1,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
  [654] = 1,
    ACTIONS(198), 1,
      anon_sym_SEMI,
  [658] = 1,
    ACTIONS(200), 1,
      anon_sym_EQ,
  [662] = 1,
    ACTIONS(202), 1,
      sym_identifier,
  [666] = 1,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
  [670] = 1,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
  [674] = 1,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
  [678] = 1,
    ACTIONS(210), 1,
      anon_sym_function,
  [682] = 1,
    ACTIONS(212), 1,
      anon_sym_PLUS,
  [686] = 1,
    ACTIONS(214), 1,
      anon_sym_SEMI,
  [690] = 1,
    ACTIONS(216), 1,
      anon_sym_SEMI,
  [694] = 1,
    ACTIONS(218), 1,
      anon_sym_SEMI,
  [698] = 1,
    ACTIONS(220), 1,
      anon_sym_SEMI,
  [702] = 1,
    ACTIONS(222), 1,
      sym_identifier,
  [706] = 1,
    ACTIONS(224), 1,
      anon_sym_SEMI,
  [710] = 1,
    ACTIONS(226), 1,
      anon_sym_SEMI,
  [714] = 1,
    ACTIONS(228), 1,
      anon_sym_SEMI,
  [718] = 1,
    ACTIONS(230), 1,
      anon_sym_SEMI,
  [722] = 1,
    ACTIONS(232), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 75,
  [SMALL_STATE(6)] = 94,
  [SMALL_STATE(7)] = 107,
  [SMALL_STATE(8)] = 120,
  [SMALL_STATE(9)] = 139,
  [SMALL_STATE(10)] = 147,
  [SMALL_STATE(11)] = 155,
  [SMALL_STATE(12)] = 163,
  [SMALL_STATE(13)] = 171,
  [SMALL_STATE(14)] = 179,
  [SMALL_STATE(15)] = 187,
  [SMALL_STATE(16)] = 195,
  [SMALL_STATE(17)] = 203,
  [SMALL_STATE(18)] = 211,
  [SMALL_STATE(19)] = 219,
  [SMALL_STATE(20)] = 227,
  [SMALL_STATE(21)] = 235,
  [SMALL_STATE(22)] = 243,
  [SMALL_STATE(23)] = 259,
  [SMALL_STATE(24)] = 267,
  [SMALL_STATE(25)] = 275,
  [SMALL_STATE(26)] = 289,
  [SMALL_STATE(27)] = 297,
  [SMALL_STATE(28)] = 305,
  [SMALL_STATE(29)] = 317,
  [SMALL_STATE(30)] = 330,
  [SMALL_STATE(31)] = 343,
  [SMALL_STATE(32)] = 356,
  [SMALL_STATE(33)] = 369,
  [SMALL_STATE(34)] = 382,
  [SMALL_STATE(35)] = 395,
  [SMALL_STATE(36)] = 408,
  [SMALL_STATE(37)] = 421,
  [SMALL_STATE(38)] = 430,
  [SMALL_STATE(39)] = 440,
  [SMALL_STATE(40)] = 448,
  [SMALL_STATE(41)] = 458,
  [SMALL_STATE(42)] = 464,
  [SMALL_STATE(43)] = 470,
  [SMALL_STATE(44)] = 478,
  [SMALL_STATE(45)] = 486,
  [SMALL_STATE(46)] = 493,
  [SMALL_STATE(47)] = 500,
  [SMALL_STATE(48)] = 507,
  [SMALL_STATE(49)] = 514,
  [SMALL_STATE(50)] = 521,
  [SMALL_STATE(51)] = 526,
  [SMALL_STATE(52)] = 531,
  [SMALL_STATE(53)] = 536,
  [SMALL_STATE(54)] = 541,
  [SMALL_STATE(55)] = 548,
  [SMALL_STATE(56)] = 553,
  [SMALL_STATE(57)] = 560,
  [SMALL_STATE(58)] = 567,
  [SMALL_STATE(59)] = 574,
  [SMALL_STATE(60)] = 581,
  [SMALL_STATE(61)] = 588,
  [SMALL_STATE(62)] = 595,
  [SMALL_STATE(63)] = 602,
  [SMALL_STATE(64)] = 606,
  [SMALL_STATE(65)] = 610,
  [SMALL_STATE(66)] = 614,
  [SMALL_STATE(67)] = 618,
  [SMALL_STATE(68)] = 622,
  [SMALL_STATE(69)] = 626,
  [SMALL_STATE(70)] = 630,
  [SMALL_STATE(71)] = 634,
  [SMALL_STATE(72)] = 638,
  [SMALL_STATE(73)] = 642,
  [SMALL_STATE(74)] = 646,
  [SMALL_STATE(75)] = 650,
  [SMALL_STATE(76)] = 654,
  [SMALL_STATE(77)] = 658,
  [SMALL_STATE(78)] = 662,
  [SMALL_STATE(79)] = 666,
  [SMALL_STATE(80)] = 670,
  [SMALL_STATE(81)] = 674,
  [SMALL_STATE(82)] = 678,
  [SMALL_STATE(83)] = 682,
  [SMALL_STATE(84)] = 686,
  [SMALL_STATE(85)] = 690,
  [SMALL_STATE(86)] = 694,
  [SMALL_STATE(87)] = 698,
  [SMALL_STATE(88)] = 702,
  [SMALL_STATE(89)] = 706,
  [SMALL_STATE(90)] = 710,
  [SMALL_STATE(91)] = 714,
  [SMALL_STATE(92)] = 718,
  [SMALL_STATE(93)] = 722,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 5),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 5), SHIFT_REPEAT(82),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 5), SHIFT_REPEAT(88),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 5), SHIFT_REPEAT(69),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 5), SHIFT_REPEAT(74),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__components, 1, 0, 4),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entity, 3, 0, 6),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_def, 4, 0, 8),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__namespace_def, 4, 0, 9),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_block, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_def, 5, 0, 11),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__components, 1, 0, 2),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__components, 1, 0, 3),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_block, 3, 0, 14),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bind_id_to_type, 3, 0, 16),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_def, 6, 0, 17),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 3, 0, 12),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_block_repeat1, 2, 0, 13),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_block_repeat1, 2, 0, 13), SHIFT_REPEAT(37),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_def, 7, 0, 19),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 4, 0, 12),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 13),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 13), SHIFT_REPEAT(70),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 2, 0, 15),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 2, 0, 15), SHIFT_REPEAT(48),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 1, 0, 7),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assertion, 4, 0, 20),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_block_repeat1, 1, 0, 7),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__less_than, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__less_than, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__greater_than, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__greater_than, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 1, 0, 10),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 7),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 3, 0, 12),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field, 3, 0, 18),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__return, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [196] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__return, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 4, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 4, 0, 7),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 5, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 5, 0, 12),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__addition, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bosque(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bosque",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
