/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 89
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_public = 1,
  anon_sym_function = 2,
  anon_sym_COLON = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_return = 7,
  anon_sym_SEMI = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_declare = 11,
  anon_sym_namespace = 12,
  anon_sym_entity = 13,
  anon_sym_assert = 14,
  anon_sym_field = 15,
  anon_sym_let = 16,
  anon_sym_EQ = 17,
  anon_sym_GT = 18,
  anon_sym_GT_EQ = 19,
  anon_sym_LT = 20,
  anon_sym_LT_EQ = 21,
  anon_sym_PLUS = 22,
  anon_sym_Int = 23,
  anon_sym_Nat = 24,
  anon_sym_CString = 25,
  anon_sym_String = 26,
  sym_namespace_tok = 27,
  sym_identifier = 28,
  sym_source_file = 29,
  sym__components = 30,
  sym__function_def = 31,
  sym__parameters = 32,
  sym__return = 33,
  sym__statement_block = 34,
  sym__namespace_def = 35,
  sym__entity = 36,
  sym__field_block = 37,
  sym__assertion = 38,
  sym__field = 39,
  sym__definition = 40,
  sym__expression = 41,
  sym__less_than = 42,
  sym__greater_than = 43,
  sym__addition = 44,
  sym__bind_id_to_type = 45,
  sym__type = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym__parameters_repeat1 = 48,
  aux_sym__statement_block_repeat1 = 49,
  aux_sym__field_block_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_public] = "public",
  [anon_sym_function] = "function",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_return] = "return",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_declare] = "declare",
  [anon_sym_namespace] = "namespace",
  [anon_sym_entity] = "entity",
  [anon_sym_assert] = "assert",
  [anon_sym_field] = "field",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_PLUS] = "+",
  [anon_sym_Int] = "Int",
  [anon_sym_Nat] = "Nat",
  [anon_sym_CString] = "CString",
  [anon_sym_String] = "String",
  [sym_namespace_tok] = "namespace_tok",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__components] = "_components",
  [sym__function_def] = "_function_def",
  [sym__parameters] = "_parameters",
  [sym__return] = "_return",
  [sym__statement_block] = "_statement_block",
  [sym__namespace_def] = "_namespace_def",
  [sym__entity] = "_entity",
  [sym__field_block] = "_field_block",
  [sym__assertion] = "_assertion",
  [sym__field] = "_field",
  [sym__definition] = "_definition",
  [sym__expression] = "_expression",
  [sym__less_than] = "_less_than",
  [sym__greater_than] = "_greater_than",
  [sym__addition] = "_addition",
  [sym__bind_id_to_type] = "_bind_id_to_type",
  [sym__type] = "_type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__parameters_repeat1] = "_parameters_repeat1",
  [aux_sym__statement_block_repeat1] = "_statement_block_repeat1",
  [aux_sym__field_block_repeat1] = "_field_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_public] = anon_sym_public,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_declare] = anon_sym_declare,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_entity] = anon_sym_entity,
  [anon_sym_assert] = anon_sym_assert,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_Int] = anon_sym_Int,
  [anon_sym_Nat] = anon_sym_Nat,
  [anon_sym_CString] = anon_sym_CString,
  [anon_sym_String] = anon_sym_String,
  [sym_namespace_tok] = sym_namespace_tok,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__components] = sym__components,
  [sym__function_def] = sym__function_def,
  [sym__parameters] = sym__parameters,
  [sym__return] = sym__return,
  [sym__statement_block] = sym__statement_block,
  [sym__namespace_def] = sym__namespace_def,
  [sym__entity] = sym__entity,
  [sym__field_block] = sym__field_block,
  [sym__assertion] = sym__assertion,
  [sym__field] = sym__field,
  [sym__definition] = sym__definition,
  [sym__expression] = sym__expression,
  [sym__less_than] = sym__less_than,
  [sym__greater_than] = sym__greater_than,
  [sym__addition] = sym__addition,
  [sym__bind_id_to_type] = sym__bind_id_to_type,
  [sym__type] = sym__type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__parameters_repeat1] = aux_sym__parameters_repeat1,
  [aux_sym__statement_block_repeat1] = aux_sym__statement_block_repeat1,
  [aux_sym__field_block_repeat1] = aux_sym__field_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_public] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_declare] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entity] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assert] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Nat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CString] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [sym_namespace_tok] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__components] = {
    .visible = false,
    .named = true,
  },
  [sym__function_def] = {
    .visible = false,
    .named = true,
  },
  [sym__parameters] = {
    .visible = false,
    .named = true,
  },
  [sym__return] = {
    .visible = false,
    .named = true,
  },
  [sym__statement_block] = {
    .visible = false,
    .named = true,
  },
  [sym__namespace_def] = {
    .visible = false,
    .named = true,
  },
  [sym__entity] = {
    .visible = false,
    .named = true,
  },
  [sym__field_block] = {
    .visible = false,
    .named = true,
  },
  [sym__assertion] = {
    .visible = false,
    .named = true,
  },
  [sym__field] = {
    .visible = false,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__less_than] = {
    .visible = false,
    .named = true,
  },
  [sym__greater_than] = {
    .visible = false,
    .named = true,
  },
  [sym__addition] = {
    .visible = false,
    .named = true,
  },
  [sym__bind_id_to_type] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__field_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_bsq_prim = 2,
  field_entity_name = 3,
  field_fields = 4,
  field_func_name = 5,
  field_name = 6,
  field_params = 7,
  field_return_type = 8,
  field_token = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_bsq_prim] = "bsq_prim",
  [field_entity_name] = "entity_name",
  [field_fields] = "fields",
  [field_func_name] = "func_name",
  [field_name] = "name",
  [field_params] = "params",
  [field_return_type] = "return_type",
  [field_token] = "token",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 9},
  [2] = {.index = 9, .length = 5},
  [3] = {.index = 14, .length = 1},
  [4] = {.index = 15, .length = 4},
  [5] = {.index = 19, .length = 18},
  [6] = {.index = 37, .length = 1},
  [7] = {.index = 38, .length = 4},
  [8] = {.index = 42, .length = 1},
  [9] = {.index = 43, .length = 1},
  [10] = {.index = 44, .length = 2},
  [11] = {.index = 46, .length = 1},
  [12] = {.index = 47, .length = 7},
  [13] = {.index = 54, .length = 7},
  [14] = {.index = 61, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 0, .inherited = true},
    {field_bsq_prim, 0, .inherited = true},
    {field_entity_name, 0, .inherited = true},
    {field_fields, 0, .inherited = true},
    {field_func_name, 0, .inherited = true},
    {field_name, 0, .inherited = true},
    {field_params, 0, .inherited = true},
    {field_return_type, 0, .inherited = true},
    {field_token, 0, .inherited = true},
  [9] =
    {field_body, 0, .inherited = true},
    {field_bsq_prim, 0, .inherited = true},
    {field_func_name, 0, .inherited = true},
    {field_params, 0, .inherited = true},
    {field_return_type, 0, .inherited = true},
  [14] =
    {field_name, 0, .inherited = true},
  [15] =
    {field_bsq_prim, 0, .inherited = true},
    {field_entity_name, 0, .inherited = true},
    {field_fields, 0, .inherited = true},
    {field_token, 0, .inherited = true},
  [19] =
    {field_body, 0, .inherited = true},
    {field_body, 1, .inherited = true},
    {field_bsq_prim, 0, .inherited = true},
    {field_bsq_prim, 1, .inherited = true},
    {field_entity_name, 0, .inherited = true},
    {field_entity_name, 1, .inherited = true},
    {field_fields, 0, .inherited = true},
    {field_fields, 1, .inherited = true},
    {field_func_name, 0, .inherited = true},
    {field_func_name, 1, .inherited = true},
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
    {field_params, 0, .inherited = true},
    {field_params, 1, .inherited = true},
    {field_return_type, 0, .inherited = true},
    {field_return_type, 1, .inherited = true},
    {field_token, 0, .inherited = true},
    {field_token, 1, .inherited = true},
  [37] =
    {field_name, 2},
  [38] =
    {field_bsq_prim, 2, .inherited = true},
    {field_entity_name, 1},
    {field_fields, 2},
    {field_token, 0},
  [42] =
    {field_bsq_prim, 0, .inherited = true},
  [43] =
    {field_bsq_prim, 1, .inherited = true},
  [44] =
    {field_bsq_prim, 0, .inherited = true},
    {field_bsq_prim, 1, .inherited = true},
  [46] =
    {field_bsq_prim, 2},
  [47] =
    {field_body, 5},
    {field_bsq_prim, 2, .inherited = true},
    {field_bsq_prim, 4},
    {field_bsq_prim, 5, .inherited = true},
    {field_func_name, 1},
    {field_params, 2},
    {field_return_type, 3},
  [54] =
    {field_body, 6},
    {field_bsq_prim, 3, .inherited = true},
    {field_bsq_prim, 5},
    {field_bsq_prim, 6, .inherited = true},
    {field_func_name, 2},
    {field_params, 3},
    {field_return_type, 4},
  [61] =
    {field_bsq_prim, 2, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(64);
      ADVANCE_MAP(
        '(', 68,
        ')', 70,
        '+', 87,
        ',', 69,
        ':', 67,
        ';', 72,
        '<', 85,
        '=', 82,
        '>', 83,
        'C', 2,
        'I', 37,
        'N', 4,
        'S', 51,
        'a', 49,
        'd', 13,
        'e', 40,
        'f', 25,
        'l', 19,
        'n', 3,
        'p', 61,
        'r', 20,
        '{', 73,
        '}', 74,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(70);
      if (lookahead == ',') ADVANCE(69);
      if (lookahead == ';') ADVANCE(72);
      if (lookahead == '=') ADVANCE(82);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(92);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 2:
      if (lookahead == 'S') ADVANCE(60);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'b') ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(65);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(59);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(79);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(75);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 21:
      if (lookahead == 'g') ADVANCE(91);
      END_STATE();
    case 22:
      if (lookahead == 'g') ADVANCE(90);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(17);
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 33:
      if (lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(71);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 41:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 42:
      if (lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 48:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(50);
      END_STATE();
    case 50:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(88);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(89);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 56:
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 57:
      if (lookahead == 't') ADVANCE(62);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 61:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 62:
      if (lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 63:
      if (lookahead == 'y') ADVANCE(77);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_public);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_declare);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_entity);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_assert);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_let);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(86);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_Int);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_Nat);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_CString);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_namespace_tok);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(94);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(81);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 30},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 30},
  [47] = {.lex_state = 30},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_public] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_declare] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_entity] = ACTIONS(1),
    [anon_sym_assert] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_Int] = ACTIONS(1),
    [anon_sym_Nat] = ACTIONS(1),
    [anon_sym_CString] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(57),
    [sym__components] = STATE(24),
    [sym__function_def] = STATE(20),
    [sym__namespace_def] = STATE(7),
    [sym__entity] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_public] = ACTIONS(5),
    [anon_sym_function] = ACTIONS(7),
    [anon_sym_declare] = ACTIONS(9),
    [anon_sym_entity] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(5), 1,
      anon_sym_public,
    ACTIONS(7), 1,
      anon_sym_function,
    ACTIONS(9), 1,
      anon_sym_declare,
    ACTIONS(11), 1,
      anon_sym_entity,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(7), 1,
      sym__namespace_def,
    STATE(16), 1,
      sym__entity,
    STATE(20), 1,
      sym__function_def,
    STATE(24), 1,
      sym__components,
  [31] = 10,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_public,
    ACTIONS(20), 1,
      anon_sym_function,
    ACTIONS(23), 1,
      anon_sym_declare,
    ACTIONS(26), 1,
      anon_sym_entity,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(7), 1,
      sym__namespace_def,
    STATE(16), 1,
      sym__entity,
    STATE(20), 1,
      sym__function_def,
    STATE(24), 1,
      sym__components,
  [62] = 6,
    ACTIONS(29), 1,
      anon_sym_return,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(33), 1,
      anon_sym_assert,
    STATE(5), 1,
      aux_sym__statement_block_repeat1,
    STATE(34), 1,
      sym__assertion,
    STATE(73), 1,
      sym__return,
  [81] = 6,
    ACTIONS(29), 1,
      anon_sym_return,
    ACTIONS(33), 1,
      anon_sym_assert,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      aux_sym__statement_block_repeat1,
    STATE(34), 1,
      sym__assertion,
    STATE(58), 1,
      sym__return,
  [100] = 4,
    ACTIONS(39), 1,
      anon_sym_assert,
    STATE(6), 1,
      aux_sym__statement_block_repeat1,
    STATE(34), 1,
      sym__assertion,
    ACTIONS(37), 2,
      anon_sym_return,
      anon_sym_RBRACE,
  [114] = 1,
    ACTIONS(42), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [122] = 1,
    ACTIONS(44), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [130] = 1,
    ACTIONS(46), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [138] = 2,
    STATE(42), 1,
      sym__type,
    ACTIONS(48), 4,
      anon_sym_Int,
      anon_sym_Nat,
      anon_sym_CString,
      anon_sym_String,
  [148] = 1,
    ACTIONS(50), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [156] = 2,
    STATE(38), 1,
      sym__type,
    ACTIONS(52), 4,
      anon_sym_Int,
      anon_sym_Nat,
      anon_sym_CString,
      anon_sym_String,
  [166] = 2,
    STATE(15), 1,
      sym__type,
    ACTIONS(54), 4,
      anon_sym_Int,
      anon_sym_Nat,
      anon_sym_CString,
      anon_sym_String,
  [176] = 1,
    ACTIONS(56), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [184] = 1,
    ACTIONS(58), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ,
      sym_identifier,
  [192] = 1,
    ACTIONS(60), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [200] = 1,
    ACTIONS(62), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [208] = 1,
    ACTIONS(64), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [216] = 1,
    ACTIONS(66), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [224] = 1,
    ACTIONS(68), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [232] = 1,
    ACTIONS(70), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [240] = 1,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [248] = 1,
    ACTIONS(74), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [256] = 1,
    ACTIONS(76), 5,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_function,
      anon_sym_declare,
      anon_sym_entity,
  [264] = 4,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    ACTIONS(80), 1,
      sym_identifier,
    STATE(26), 1,
      aux_sym__parameters_repeat1,
    STATE(36), 1,
      sym__bind_id_to_type,
  [277] = 4,
    ACTIONS(80), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      aux_sym__parameters_repeat1,
    STATE(36), 1,
      sym__bind_id_to_type,
  [290] = 4,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    ACTIONS(86), 1,
      anon_sym_field,
    STATE(27), 1,
      aux_sym__field_block_repeat1,
    STATE(40), 1,
      sym__field,
  [303] = 2,
    ACTIONS(89), 1,
      sym_identifier,
    STATE(32), 3,
      sym__expression,
      sym__less_than,
      sym__greater_than,
  [312] = 4,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    ACTIONS(93), 1,
      anon_sym_field,
    STATE(27), 1,
      aux_sym__field_block_repeat1,
    STATE(40), 1,
      sym__field,
  [325] = 4,
    ACTIONS(93), 1,
      anon_sym_field,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      aux_sym__field_block_repeat1,
    STATE(40), 1,
      sym__field,
  [338] = 4,
    ACTIONS(97), 1,
      anon_sym_GT,
    ACTIONS(99), 1,
      anon_sym_GT_EQ,
    ACTIONS(101), 1,
      anon_sym_LT,
    ACTIONS(103), 1,
      anon_sym_LT_EQ,
  [351] = 4,
    ACTIONS(105), 1,
      anon_sym_let,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(65), 1,
      sym__definition,
    STATE(66), 1,
      sym__bind_id_to_type,
  [364] = 4,
    ACTIONS(109), 1,
      anon_sym_RPAREN,
    ACTIONS(111), 1,
      sym_identifier,
    STATE(33), 1,
      aux_sym__parameters_repeat1,
    STATE(36), 1,
      sym__bind_id_to_type,
  [377] = 1,
    ACTIONS(114), 3,
      anon_sym_return,
      anon_sym_RBRACE,
      anon_sym_assert,
  [383] = 1,
    ACTIONS(116), 3,
      anon_sym_return,
      anon_sym_RBRACE,
      anon_sym_assert,
  [389] = 2,
    ACTIONS(118), 1,
      anon_sym_COMMA,
    ACTIONS(120), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [397] = 2,
    ACTIONS(80), 1,
      sym_identifier,
    STATE(83), 1,
      sym__bind_id_to_type,
  [404] = 2,
    ACTIONS(122), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      sym__statement_block,
  [411] = 1,
    ACTIONS(124), 2,
      anon_sym_RBRACE,
      anon_sym_field,
  [416] = 1,
    ACTIONS(126), 2,
      anon_sym_RBRACE,
      anon_sym_field,
  [421] = 2,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    STATE(68), 1,
      sym__parameters,
  [428] = 2,
    ACTIONS(122), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym__statement_block,
  [435] = 2,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(88), 1,
      sym__bind_id_to_type,
  [442] = 2,
    ACTIONS(132), 1,
      anon_sym_COLON,
    ACTIONS(134), 1,
      anon_sym_EQ,
  [449] = 2,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    STATE(59), 1,
      sym__parameters,
  [456] = 1,
    ACTIONS(136), 2,
      anon_sym_let,
      sym_identifier,
  [461] = 1,
    ACTIONS(138), 2,
      anon_sym_let,
      sym_identifier,
  [466] = 2,
    ACTIONS(132), 1,
      anon_sym_COLON,
    ACTIONS(140), 1,
      anon_sym_EQ,
  [473] = 2,
    ACTIONS(142), 1,
      sym_identifier,
    STATE(78), 1,
      sym__addition,
  [480] = 1,
    ACTIONS(144), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [485] = 2,
    ACTIONS(142), 1,
      sym_identifier,
    STATE(79), 1,
      sym__addition,
  [492] = 2,
    ACTIONS(142), 1,
      sym_identifier,
    STATE(80), 1,
      sym__addition,
  [499] = 2,
    ACTIONS(142), 1,
      sym_identifier,
    STATE(81), 1,
      sym__addition,
  [506] = 2,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym__field_block,
  [513] = 1,
    ACTIONS(148), 1,
      anon_sym_SEMI,
  [517] = 1,
    ACTIONS(150), 1,
      sym_namespace_tok,
  [521] = 1,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
  [525] = 1,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
  [529] = 1,
    ACTIONS(156), 1,
      anon_sym_COLON,
  [533] = 1,
    ACTIONS(158), 1,
      anon_sym_RBRACE,
  [537] = 1,
    ACTIONS(160), 1,
      sym_identifier,
  [541] = 1,
    ACTIONS(162), 1,
      sym_identifier,
  [545] = 1,
    ACTIONS(164), 1,
      sym_identifier,
  [549] = 1,
    ACTIONS(166), 1,
      anon_sym_function,
  [553] = 1,
    ACTIONS(168), 1,
      anon_sym_SEMI,
  [557] = 1,
    ACTIONS(170), 1,
      anon_sym_EQ,
  [561] = 1,
    ACTIONS(172), 1,
      sym_namespace_tok,
  [565] = 1,
    ACTIONS(174), 1,
      anon_sym_COLON,
  [569] = 1,
    ACTIONS(176), 1,
      sym_identifier,
  [573] = 1,
    ACTIONS(178), 1,
      anon_sym_COLON,
  [577] = 1,
    ACTIONS(180), 1,
      anon_sym_namespace,
  [581] = 1,
    ACTIONS(182), 1,
      anon_sym_COLON,
  [585] = 1,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
  [589] = 1,
    ACTIONS(132), 1,
      anon_sym_COLON,
  [593] = 1,
    ACTIONS(186), 1,
      sym_identifier,
  [597] = 1,
    ACTIONS(188), 1,
      anon_sym_SEMI,
  [601] = 1,
    ACTIONS(190), 1,
      anon_sym_PLUS,
  [605] = 1,
    ACTIONS(192), 1,
      anon_sym_SEMI,
  [609] = 1,
    ACTIONS(194), 1,
      anon_sym_SEMI,
  [613] = 1,
    ACTIONS(196), 1,
      anon_sym_SEMI,
  [617] = 1,
    ACTIONS(198), 1,
      anon_sym_SEMI,
  [621] = 1,
    ACTIONS(200), 1,
      sym_identifier,
  [625] = 1,
    ACTIONS(202), 1,
      anon_sym_SEMI,
  [629] = 1,
    ACTIONS(204), 1,
      anon_sym_SEMI,
  [633] = 1,
    ACTIONS(206), 1,
      anon_sym_SEMI,
  [637] = 1,
    ACTIONS(208), 1,
      anon_sym_SEMI,
  [641] = 1,
    ACTIONS(210), 1,
      anon_sym_SEMI,
  [645] = 1,
    ACTIONS(212), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 81,
  [SMALL_STATE(6)] = 100,
  [SMALL_STATE(7)] = 114,
  [SMALL_STATE(8)] = 122,
  [SMALL_STATE(9)] = 130,
  [SMALL_STATE(10)] = 138,
  [SMALL_STATE(11)] = 148,
  [SMALL_STATE(12)] = 156,
  [SMALL_STATE(13)] = 166,
  [SMALL_STATE(14)] = 176,
  [SMALL_STATE(15)] = 184,
  [SMALL_STATE(16)] = 192,
  [SMALL_STATE(17)] = 200,
  [SMALL_STATE(18)] = 208,
  [SMALL_STATE(19)] = 216,
  [SMALL_STATE(20)] = 224,
  [SMALL_STATE(21)] = 232,
  [SMALL_STATE(22)] = 240,
  [SMALL_STATE(23)] = 248,
  [SMALL_STATE(24)] = 256,
  [SMALL_STATE(25)] = 264,
  [SMALL_STATE(26)] = 277,
  [SMALL_STATE(27)] = 290,
  [SMALL_STATE(28)] = 303,
  [SMALL_STATE(29)] = 312,
  [SMALL_STATE(30)] = 325,
  [SMALL_STATE(31)] = 338,
  [SMALL_STATE(32)] = 351,
  [SMALL_STATE(33)] = 364,
  [SMALL_STATE(34)] = 377,
  [SMALL_STATE(35)] = 383,
  [SMALL_STATE(36)] = 389,
  [SMALL_STATE(37)] = 397,
  [SMALL_STATE(38)] = 404,
  [SMALL_STATE(39)] = 411,
  [SMALL_STATE(40)] = 416,
  [SMALL_STATE(41)] = 421,
  [SMALL_STATE(42)] = 428,
  [SMALL_STATE(43)] = 435,
  [SMALL_STATE(44)] = 442,
  [SMALL_STATE(45)] = 449,
  [SMALL_STATE(46)] = 456,
  [SMALL_STATE(47)] = 461,
  [SMALL_STATE(48)] = 466,
  [SMALL_STATE(49)] = 473,
  [SMALL_STATE(50)] = 480,
  [SMALL_STATE(51)] = 485,
  [SMALL_STATE(52)] = 492,
  [SMALL_STATE(53)] = 499,
  [SMALL_STATE(54)] = 506,
  [SMALL_STATE(55)] = 513,
  [SMALL_STATE(56)] = 517,
  [SMALL_STATE(57)] = 521,
  [SMALL_STATE(58)] = 525,
  [SMALL_STATE(59)] = 529,
  [SMALL_STATE(60)] = 533,
  [SMALL_STATE(61)] = 537,
  [SMALL_STATE(62)] = 541,
  [SMALL_STATE(63)] = 545,
  [SMALL_STATE(64)] = 549,
  [SMALL_STATE(65)] = 553,
  [SMALL_STATE(66)] = 557,
  [SMALL_STATE(67)] = 561,
  [SMALL_STATE(68)] = 565,
  [SMALL_STATE(69)] = 569,
  [SMALL_STATE(70)] = 573,
  [SMALL_STATE(71)] = 577,
  [SMALL_STATE(72)] = 581,
  [SMALL_STATE(73)] = 585,
  [SMALL_STATE(74)] = 589,
  [SMALL_STATE(75)] = 593,
  [SMALL_STATE(76)] = 597,
  [SMALL_STATE(77)] = 601,
  [SMALL_STATE(78)] = 605,
  [SMALL_STATE(79)] = 609,
  [SMALL_STATE(80)] = 613,
  [SMALL_STATE(81)] = 617,
  [SMALL_STATE(82)] = 621,
  [SMALL_STATE(83)] = 625,
  [SMALL_STATE(84)] = 629,
  [SMALL_STATE(85)] = 633,
  [SMALL_STATE(86)] = 637,
  [SMALL_STATE(87)] = 641,
  [SMALL_STATE(88)] = 645,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 5),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 5), SHIFT_REPEAT(64),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 5), SHIFT_REPEAT(75),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 5), SHIFT_REPEAT(71),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 5), SHIFT_REPEAT(56),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_block_repeat1, 2, 0, 10),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_block_repeat1, 2, 0, 10), SHIFT_REPEAT(28),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__components, 1, 0, 3),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__namespace_def, 3, 0, 6),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__entity, 3, 0, 7),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_block, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_block, 3, 0, 9),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bind_id_to_type, 3, 0, 11),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__components, 1, 0, 4),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_def, 6, 0, 12),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_def, 7, 0, 13),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__components, 1, 0, 2),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 3, 0, 9),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_block, 4, 0, 9),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 2, 0, 10),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 2, 0, 10), SHIFT_REPEAT(37),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 10),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 10), SHIFT_REPEAT(74),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_block_repeat1, 1, 0, 8),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assertion, 4, 0, 14),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 1, 0, 8),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field, 3, 0, 9),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__field_block_repeat1, 1, 0, 8),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__less_than, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__greater_than, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 8),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 4, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [152] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__return, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 3, 0, 9),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 4, 0, 8),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 5, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 5, 0, 9),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__addition, 3, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bosque(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bosque",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
